<a href="https://colab.research.google.com/github/mohinilodhi/python-library/blob/main/pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [224]:
df.head()

       Nmae  age  marks status
0      aman   18     80   pass
1    aditya   19     90   fail
2     rahul   20     88   pass
3  aakancha   18     89   pass
4     jyoti   19     99   fail

In [225]:
import pandas as pd

data = {
    "Nmae":["aman","aditya","rahul","aakancha","jyoti"],
    "age":[18,19,20,18,19],
    "marks":[80,90,88,89,99]
}
df = pd.DataFrame(data)
print(df)

       Nmae  age  marks
0      aman   18     80
1    aditya   19     90
2     rahul   20     88
3  aakancha   18     89
4     jyoti   19     99

In [226]:
df.tail()

       Nmae  age  marks
0      aman   18     80
1    aditya   19     90
2     rahul   20     88
3  aakancha   18     89
4     jyoti   19     99

In [227]:
df.shape

(5, 3)

In [228]:
df.size

15

In [229]:
df.columns

Index(['Nmae', 'age', 'marks'], dtype='object')

In [230]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Nmae    5 non-null      object
 1   age     5 non-null      int64
 2   marks   5 non-null      int64
dtypes: int64(2), object(1)
memory usage: 252.0+ bytes

In [231]:
df["Nmae"]

0        aman
1      aditya
2       rahul
3    aakancha
4       jyoti
Name: Nmae, dtype: object

In [232]:
df["marks"]

0    80
1    90
2    88
3    89
4    99
Name: marks, dtype: int64

In [233]:
df[["Nmae","age"]]

       Nmae  age
0      aman   18
1    aditya   19
2     rahul   20
3  aakancha   18
4     jyoti   19

In [234]:
df["marks"].mean()

np.float64(89.2)

In [235]:
df["marks"].max()

99

In [236]:
df["marks"].min()

80

In [237]:
df["marks"].sum()

np.int64(446)

In [238]:
df[df["marks"] > 80]

       Nmae  age  marks
1    aditya   19     90
2     rahul   20     88
3  aakancha   18     89
4     jyoti   19     99

In [239]:
df[df["age"] == 18]

       Nmae  age  marks
0      aman   18     80
3  aakancha   18     89

In [240]:
df.sort_values(by="marks")

       Nmae  age  marks
0      aman   18     80
2     rahul   20     88
3  aakancha   18     89
1    aditya   19     90
4     jyoti   19     99

In [241]:
df.sort_values(by="marks",ascending=False)

       Nmae  age  marks
4     jyoti   19     99
1    aditya   19     90
3  aakancha   18     89
2     rahul   20     88
0      aman   18     80

In [242]:
df["status"] = ["pass","fail","pass","pass","fail"]
print(df)

       Nmae  age  marks status
0      aman   18     80   pass
1    aditya   19     90   fail
2     rahul   20     88   pass
3  aakancha   18     89   pass
4     jyoti   19     99   fail